export enum BillingTypeEnum {
  FREE_TRIAL = "FREE_TRIAL",
  MONTHLY_FIXED = "MONTHLY_FIXED",
  QUARTERLY_FIXED = "QUARTERLY_FIXED",
  HALF_YEARLY_FIXED = "HALF_YEARLY_FIXED",
  YEARLY_FIXED = "YEARLY_FIXED",
  PAY_AS_YOU_GO = "PAY_AS_YOU_GO",
}

export enum PlanIntervalEnum {
  MONTHLY = "MONTHLY",
  QUARTERLY = "QUARTERLY",
  HALF_YEARLY = "HALF_YEARLY",
  YEARLY = "YEARLY",
  PAY_AS_YOU_GO = "PAY_AS_YOU_GO",
}
export enum SubscriptionsStatus {
  ACTIVE = "ACTIVE",
  TRIALING = "TRIALING",
  PAUSED = "PAUSED",
  CANCELED = "CANCELED",
  EXPIRED = "EXPIRED",
}
